# Generated by Django 5.1.3 on 2024-12-12 07:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Fecha cuando se crea el registro', null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Fecha cuando se modifica el registro')),
                ('archivo', models.FileField(blank=True, max_length=128, null=True, upload_to='media', verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('TOPICO', 'Topicos'), ('PARROQUIA', 'Parroquias'), ('HECHO', 'Hechos'), ('DATA', 'Data Recolectada')], default='HECHO', max_length=20)),
                ('usuario_creacion', models.ForeignKey(blank=True, help_text='Usuario que crea el registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_usuario_creacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, help_text='Usuario que modifica el registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_usuario_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='RegistroActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Fecha cuando se crea el registro', null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Fecha cuando se modifica el registro')),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.archivo')),
                ('usuario_creacion', models.ForeignKey(blank=True, help_text='Usuario que crea el registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_usuario_creacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, help_text='Usuario que modifica el registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_usuario_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actualizacion',
                'verbose_name_plural': 'Actualizaciones',
            },
        ),
    ]
