# Generated by Django 5.1.3 on 2024-12-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_archivo_fecha_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='cargado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
