# Generated by Django 5.1.3 on 2025-01-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_archivo_cargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecha',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fecha',
            name='semana',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
