# Generated by Django 5.1.3 on 2025-01-30 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fecha_anio_fecha_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='HechoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tweets', models.IntegerField()),
                ('fecha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fecha')),
                ('topico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.topico')),
            ],
            options={
                'verbose_name': 'Hecho General',
                'verbose_name_plural': 'Hechos Generales',
            },
        ),
    ]
